# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Prod

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Deployment job
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      CI: false
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: sudo apt-get install -y zip && sudo apt-get install -y sshpass
      - name: Install yarn
        run: yarn install && yarn build:prod
      - name: Zip file build
        run: zip -r landing.zip build
      - name: Upload file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 24
          source: "landing.zip"
          target: "~/aip/landing"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 24
          script: 'cd ~/aip/landing && source deploy.sh'
