# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Prod

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Deployment job
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@main
      - name: Prepare
        run: sudo apt-get install -y zip && sudo apt-get install -y sshpass
      - name: Install yarn
        run: yarn install && yarn build:prod
      - name: Zip file build
        run: zip -r landing.zip build
      - name: Upload file
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} scp -P 24 landing.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:~/aip/landing
      - name: Deploy
        run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} -p 24 'cd ~/aip/landing && source deploy.sh'
